global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # NameNode expone métricas Prometheus en puerto 9090 via JMX Exporter
  - job_name: 'hadoop-namenode'
    static_configs:
      - targets: ['Nodo-principal2:9094']
    metrics_path: /metrics

  # DataNodes exponen métricas Prometheus en puerto 9091 via JMX Exporter
  - job_name: 'hadoop-datanode-1'
    static_configs:
      - targets: ['datos-12:9091']
    metrics_path: /metrics

  - job_name: 'hadoop-datanode-2'
    static_configs:
      - targets: ['datos-22:9091']
    metrics_path: /metrics

